from django.db import models


class Games(models.Model):
    GameId = models.AutoField(primary_key=True)
    Date = models.DateField()
    HomeTeamName = models.CharField(max_length=100)
    AwayTeamName = models.CharField(max_length=100)
    HomeTeamPts = models.IntegerField(default=0)
    AwayTeamPts = models.IntegerField(default=0)


class Predictions(models.Model):
    team = models.IntegerField(default=0)
    FGM = models.DecimalField(max_digits=12, decimal_places=5)
    FGA = models.DecimalField(max_digits=12, decimal_places=5)
    TPM = models.DecimalField(max_digits=12, decimal_places=5)
    TPA = models.DecimalField(max_digits=12, decimal_places=5)
    FTM = models.DecimalField(max_digits=12, decimal_places=5)
    FTA = models.DecimalField(max_digits=12, decimal_places=5)
    OR = models.DecimalField(max_digits=12, decimal_places=5)
    DR = models.DecimalField(max_digits=12, decimal_places=5)
    AS = models.DecimalField(max_digits=12, decimal_places=5)
    STL = models.DecimalField(max_digits=12, decimal_places=5)
    BLK = models.DecimalField(max_digits=12, decimal_places=5)
    TO = models.DecimalField(max_digits=12, decimal_places=5)
    PF = models.DecimalField(max_digits=12, decimal_places=5)
    LOC = models.CharField(max_length=100)
    OPP = models.IntegerField(default=0)
    ELO = models.DecimalField(max_digits=12, decimal_places=5)
    DEF = models.DecimalField(max_digits=12, decimal_places=5)
    team2 = models.IntegerField(default=0)
    FGM2 = models.DecimalField(max_digits=12, decimal_places=5)
    FGA2 = models.DecimalField(max_digits=12, decimal_places=5)
    TPM2 = models.DecimalField(max_digits=12, decimal_places=5)
    TPA2 = models.DecimalField(max_digits=12, decimal_places=5)
    FTM2 = models.DecimalField(max_digits=12, decimal_places=5)
    FTA2 = models.DecimalField(max_digits=12, decimal_places=5)
    OR2 = models.DecimalField(max_digits=12, decimal_places=5)
    DR2 = models.DecimalField(max_digits=12, decimal_places=5)
    AS2 = models.DecimalField(max_digits=12, decimal_places=5)
    STL2 = models.DecimalField(max_digits=12, decimal_places=5)
    BLK2 = models.DecimalField(max_digits=12, decimal_places=5)
    TO2 = models.DecimalField(max_digits=12, decimal_places=5)
    PF2 = models.DecimalField(max_digits=12, decimal_places=5)
    LOC2 = models.CharField(max_length=100)
    OPP2 = models.IntegerField(default=0)
    ELO2 = models.DecimalField(max_digits=12, decimal_places=5)
    DEF2 = models.DecimalField(max_digits=12, decimal_places=5)
    OUTCOME = models.CharField(max_length=100)

